"""empty message

Revision ID: dc193516dfcb
Revises: eb9079b8f7fc
Create Date: 2019-03-11 20:40:20.409222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc193516dfcb'
down_revision = 'eb9079b8f7fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_content_key', 'message', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('message_content_key', 'message', ['content'])
    # ### end Alembic commands ###
