"""empty message

Revision ID: eb9079b8f7fc
Revises: f5b7d68c376a
Create Date: 2019-03-11 20:16:57.145871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9079b8f7fc'
down_revision = 'f5b7d68c376a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('last_read_message_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'member', ['id'])
    op.create_foreign_key(None, 'member', 'message', ['last_read_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'member', type_='foreignkey')
    op.drop_constraint(None, 'member', type_='unique')
    op.drop_column('member', 'last_read_message_id')
    # ### end Alembic commands ###
