"""empty message

Revision ID: f5b7d68c376a
Revises: 49ebf7a0a3e6
Create Date: 2019-03-11 20:15:43.861133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b7d68c376a'
down_revision = '49ebf7a0a3e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('new_messages', sa.String(length=90), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('new_messages')
    )
    op.create_unique_constraint(None, 'chat', ['id'])
    op.create_unique_constraint(None, 'message', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'message', type_='unique')
    op.drop_constraint(None, 'chat', type_='unique')
    op.drop_table('member')
    # ### end Alembic commands ###
